<a href="https://colab.research.google.com/github/Ivon110/Mineria-de-Datos/blob/main/mineriacolab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos


##**Primer Parcial**

### Introducción




####Conceptos

**Minería de datos**

El data mining, o minería de datos, es una disciplina dentro del big data que permite analizar grandes volúmenes de información para identificar patrones, tendencias y correlaciones.

El origen de esta ciencia se remonta a la década de 1960. Sin embargo, comenzó a adquirir mayor relevancia en los años 90 y 2000, gracias al avance de las tecnologías de procesamiento de datos.

Esta tecnología se basa en un conjunto de técnicas y herramientas capaces de explorar bases de datos de forma automática o semiautomática, que transforman datos que parecen inconexos en información valiosa.

El data mining se compara con una arqueología o minería moderna, en la que los datos, de forma aislada, pueden parecer irrelevantes, pero al analizarlos en conjunto, revelan conocimientos estratégicos para la toma de decisiones.

**Ciencia de Datos**

Es un enfoque multidisciplinario que combina principios y prácticas del campo de las matemáticas, la estadística, la inteligencia artificial y la ingeniería de computación para analizar grandes cantidades de datos. Este análisis permite que los científicos de datos planteen y respondan a preguntas como “qué pasó”, “por qué pasó”, “qué pasará” y “qué se puede hacer con los resultados”, además es importante porque combina herramientas, métodos y tecnología para generar significado a partir de los datos




####Help in Python

In [10]:
#Muestra la descripción oficial de la función len()
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [11]:
#Muestra un resumen rápido de la función en IPython/Jupyter
len?

In [12]:
#Crea una lista con los elementos 1, 2 y 3
L = [1, 2, 3]

In [13]:
#Sirve para insertar un valor en la lista en la posición indicada
L.insert?

In [14]:
#Muestra información sobre el objeto L (tipo, docstring, etc.).
L?

In [15]:
#Define una función llamada square que devuelve el cuadrado de a
def square(a):
     return a ** 2

In [16]:
#Muestra inforamacón básica de la función square
square?

In [17]:
#Muestra información más detallada,  incluyendo el código fuente si está disponible
square??

In [18]:
##Muestra información más detallada,  incluyendo el código fuente si está disponible
len??

###IPython Magix Commands


In [19]:
# El comando magico %timeit sirve para evaluar el desempeño, en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

50.2 µs ± 20.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [20]:
#El comando magico %%timeit sirve para evaluar el desempeño, en terminos de tiempo
# Solo que este abarca varias lineas de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

44.7 µs ± 1.14 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [21]:
#Mide el tiempo de una sola línea
%timeit?

In [22]:
#Mide el tiempo de toda la celda
%%timeit?

IPython and Shell Commands

In [23]:
!ls

sample_data


In [24]:
%cd sample_data/

/content/sample_data


In [25]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [26]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [27]:
#Para ver las variables de entorno/ambiente
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '7f2f8f81b452',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Undestanding Data Types In Python

In [28]:
import numpy as np

In [29]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [30]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [31]:
#float 32 para la precision del flotante
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [32]:
np.array([1,2,3,4], dtype='int')

array([1, 2, 3, 4])

In [33]:
np.array([range(i, i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The Basics of NumPy Arrays

In [34]:
#Importamos NumPy
import numpy as np

In [35]:
#Generamos una semilla aleatoria
np.random.seed(0)
# Generamos un arreglo aleatorio de enteros, de tamaño seis
x1 = np.random.randint(10, size=6) #El superior no se toma en cuenta es decir va del 0 al 9
# Generamos un arreglo aleatorio de enteros, de tamaño tres renglones y cuatro columnas
x2 = np.random.randint(10, size=(3,4))
# Para hacer un arreglo tridimensional
x3 = np.random.randint(10, size=(3,4,5))

In [36]:
print("x3 ndim: ", x3.ndim) # ndim nos dice el numero de dimensiones (x3 tiene 3 dimensiones)
print("x3 shape:", x3.shape) # shape imprime su forma, regresa lo que contiene la lista
print("x3 size: ", x3.size) # size es la multiplicacion del shape 3x4=12 x 5 = 60

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [37]:
print(x2.dtype) # dtype nos dice el tamaño en bytes de cada arreglo

int64


In [38]:
#itemsize: Lista el tamaño (en bytes) de cada arreglo
print("itemsize:", x3.itemsize, "bytes")
# nbytes: Lista el tamaño total (en bytes) del arreglo
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [39]:
# Son digitos entre el 0 y 10 porque le dimos este limite desde el principio (x1 = np.random.randint(10, size=6) )

x1

array([5, 0, 3, 3, 7, 9])

In [40]:
#Colocamos el índice del elemento a extraer, en este caso el primer elemento tiene el índice 0
x1[0]

np.int64(5)

In [41]:
#Colocamos el índice del elemento a extraer, en este caso el quinto elemento tiene el índice 4
x1[4]

np.int64(7)

In [42]:
# Si queremos el ultimo elemento de ndarray (Arreglo de n dimensiones) podemos poner -1 de índice
x1[-1]

np.int64(9)

In [43]:
#Array Multidimensional
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [44]:
#Colocamos el índice del elemento a extraer, en este caso el primer elemento tiene el índice 0,0 para un indice multidimensional
x2[0,0]

np.int64(3)

In [45]:
# Renglon es la fila
# Renglon,Columna
x2[0,2]

np.int64(2)

In [46]:
x2[0,0] = 12 # Asignar un nuevo valor al renglon 0 columna 0
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])


#### Estadística Básica

Media (Mean)


In [47]:
# Uso de la Media
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [48]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [49]:
print(promedio)
print(promedio_ponderado) #Para darle un peso distinto a cada elemento

3.0
3.6666666666666665


Mediana

In [50]:
# Elemento de en medio
# No es sensible a datos aberrantes
mediana = np.median(data)

Medidas de Dispersion




*   Varianza y Desviación Estándar



In [51]:
varianza = np.var(data)
desviacion = np.std(data)

Generación de Datos Aleatorios

In [52]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra)) # Usamos medida de tendencia central que es la media y una Medida de Dispersion que es la desviacion

-0.006543456960417206 1.0059985778093545


Correlación

In [53]:
# Nos dice que tan relacionados estan dos o mas variables
# Entre mas se acerque a uno es una relacion fuerte, nos importan los extremos que son para ver el coeficiente de relacion
corr = np.corrcoef([1,2,3], [1,5,7])

Cuadros Estadísticos

In [54]:
import numpy as np
import pandas as pd
from io import StringIO

raw = """Marca temporal\tNúmero de matrícula\t¿Cuántos años cumplidos tienes?\t¿Has realizado programas utilizando Python?\t¿Has utilizado Google Colab?\t¿Tienes cuenta de GitHub?
19/01/2026 18:32:18\t178920\t22\tSi\tNo\tSi
19/01/2026 18:32:23\t182712\t21\tSi\tNo\tSi
19/01/2026 18:32:25\t180370\t26\tSi\tSi\tSi
19/01/2026 18:32:27\t182570\t21\tSi\tSi\tSi
19/01/2026 18:32:28\t177622\t24\tSi\tNo\tSi
19/01/2026 18:32:29\t175166\t22\tSi\tSi\tSi
19/01/2026 18:32:30\t177573\t22\tSi\tSi\tSi
19/01/2026 18:32:35\t178430\t21\tSi\tSi\tSi
19/01/2026 18:32:38\t179169\t23\tSi\tNo\tSi
19/01/2026 18:32:41\t177263\t22\tSi\tSi\tSi
19/01/2026 18:32:48\t179884\t23\tSi\tNo\tSi
19/01/2026 18:32:48\t183016\t22\tSi\tNo\tSi
19/01/2026 18:32:50\t179033\t23\tSi\tSi\tNo
19/01/2026 18:32:54\t178218\t22\tSi\tNo\tSi
19/01/2026 18:32:55\t178446\t22\tSi\tSi\tSi
19/01/2026 18:33:00\t178166\t22\tSi\tSi\tNo
19/01/2026 18:33:02\t177406\t22\tSi\tNo\tSi
19/01/2026 18:33:05\t177192\t22\tSi\tSi\tSi
19/01/2026 18:33:08\t182451\t21\tSi\tNo\tSi
19/01/2026 18:33:08\t171513\t24\tNo\tNo\tSi
19/01/2026 18:33:09\t181619\t21\tSi\tNo\tSi
19/01/2026 18:33:12\t182298\t23\tSi\tNo\tSi
19/01/2026 18:33:14\t181419\t24\tNo\tNo\tSi
19/01/2026 18:33:32\t177291\t21\tSi\tSi\tSi
19/01/2026 18:33:42\t182085\t22\tSi\tNo\tSi
19/01/2026 18:33:53\t176453\t22\tSi\tNo\tSi
19/01/2026 18:34:04\t176263\t24\tSi\tNo\tSi
19/01/2026 18:34:06\t179997\t21\tSi\tNo\tSi
19/01/2026 18:36:21\t175842\t23\tSi\tNo\tNo
19/01/2026 20:19:21\t179913\t20\tSi\tNo\tSi
19/01/2026 20:19:48\t177301\t22\tSi\tSi\tNo
19/01/2026 20:20:06\t183060\t21\tSi\tNo\tSi
19/01/2026 20:20:08\t177935\t22\tSi\tSi\tSi
19/01/2026 20:20:19\t177700\t20\tSi\tSi\tSi
19/01/2026 20:20:26\t178318\t24\tSi\tSi\tSi
19/01/2026 20:20:27\t174653\t24\tSi\tNo\tSi
19/01/2026 20:20:29\t177139\t21\tSi\tNo\tSi
19/01/2026 20:20:31\t173479\t25\tSi\tNo\tNo
19/01/2026 20:20:39\t175588\t23\tNo\tNo\tSi
19/01/2026 20:20:45\t178774\t23\tSi\tSi\tSi
19/01/2026 20:20:45\t175031\t23\tSi\tNo\tNo
19/01/2026 20:20:49\t178396\t21\tSi\tSi\tSi
19/01/2026 20:20:49\t172068\t23\tNo\tNo\tNo
19/01/2026 20:20:50\t174197\t23\tNo\tNo\tSi
19/01/2026 20:20:55\t178584\t22\tSi\tNo\tSi
19/01/2026 20:20:55\t175329\t24\tSi\tNo\tSi
19/01/2026 20:20:56\t177685\t22\tSi\tSi\tSi
19/01/2026 20:20:57\t178678\t22\tNo\tNo\tSi
19/01/2026 20:21:04\t177143\t22\tSi\tNo\tSi
19/01/2026 20:21:07\t182318\t26\tSi\tNo\tSi
19/01/2026 20:21:27\t182377\t20\tSi\tNo\tSi
19/01/2026 20:21:34\t179419\t22\tSi\tNo\tNo
19/01/2026 20:21:35\t181662\t21\tSi\tNo\tSi
19/01/2026 20:21:38\t181760\t21\tSi\tNo\tSi
19/01/2026 20:22:06\t177888\t22\tSi\tNo\tSi
19/01/2026 20:22:15\t176535\t25\tSi\tNo\tSi
19/01/2026 20:22:29\t179862\t21\tSi\tNo\tSi
19/01/2026 20:22:32\t178378\t22\tSi\tNo\tSi
19/01/2026 20:22:50\t177451\t22\tSi\tNo\tSi
19/01/2026 20:23:15\t179804\t21\tSi\tNo\tSi
"""

# Cargar datos
df = pd.read_csv(StringIO(raw), sep='\t')
df.columns = [c.strip() for c in df.columns]

# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce') #coerce - Ignora
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

In [55]:
df.head()

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
0  19/01/2026 18:32:18               178920                               22   
1  19/01/2026 18:32:23               182712                               21   
2  19/01/2026 18:32:25               180370                               26   
3  19/01/2026 18:32:27               182570                               21   
4  19/01/2026 18:32:28               177622                               24   

  ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
0                                          Si                           No   
1                                          Si                           No   
2                                          Si                           Si   
3                                          Si                           Si   
4                                          Si                           No   

  ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
0                        Si    22         True      False           True  
1                        Si    21         True      False           True  
2                        Si    26         True       True           True  
3                        Si    21         True       True           True  
4                        Si    24         True      False           True

In [56]:
# A NumPy
edad = df['edad'].to_numpy(dtype=float) #Toda la columna la mete a arreglo de NumPy
prog_py = df['prog_python'].to_numpy(dtype=bool)
usa_colab = df['usa_colab'].to_numpy(dtype=bool)
cuenta_gh = df['cuenta_github'].to_numpy(dtype=bool)

In [57]:
#:5 desde el principio hasta hasta el 5 (:)
edad[:5]

array([22., 21., 26., 21., 24.])

In [58]:
prog_py[:5]

array([ True,  True,  True,  True,  True])

In [59]:
# Descriptivos de edad (NumPy)
summary_age = {
    'n': int(edad.size),
    'min': float(np.min(edad)), # Para el valor minimo
    'p25': float(np.percentile(edad, 25)), #percentile genera intervalos para traer un porcentaje del totaal (Toma tanto porcentaje datos)
    'mediana': float(np.median(edad)), # Elemento de en medio - Medida Tend Central
    'media': float(np.mean(edad)), #promedio - Medida Tend Central
    'p75': float(np.percentile(edad, 75)), #75% de los datos donde se ubican los datos
    'max': float(np.max(edad)), #Edad maximma
    'rango(ptp)': float(np.ptp(edad)), #ptp - pick to peak,, del minimo al maximo cual es el rango
    'var_muestral': float(np.var(edad, ddof=1)), # var es la variancia muestral, ddof - grado de libertad - Medida Disp
    'std_muestral': float(np.std(edad, ddof=1)),# Desviacion - Medida Disp
    'cv': float(np.std(edad, ddof=1)/np.mean(edad)), #Desviacion central/media
}

In [60]:
summary_age

{'n': 60,
 'min': 20.0,
 'p25': 21.0,
 'mediana': 22.0,
 'media': 22.3,
 'p75': 23.0,
 'max': 26.0,
 'rango(ptp)': 6.0,
 'var_muestral': 1.8406779661016948,
 'std_muestral': 1.3567158752302173,
 'cv': 0.06083927691615324}

In [61]:
# Frecuencias (Cant de elementos) (NumPy)
# Creamos diccionarios
freq_python = {'Si': int(np.count_nonzero(prog_py)), 'No': int(edad.size - np.count_nonzero(prog_py))}
freq_colab  = {'Si': int(np.count_nonzero(usa_colab)), 'No': int(edad.size - np.count_nonzero(usa_colab))}
freq_gh     = {'Si': int(np.count_nonzero(cuenta_gh)), 'No': int(edad.size - np.count_nonzero(cuenta_gh))}

In [62]:
print (f"Alumnos que han utilizado de Python: {freq_python}")
print (f"Alumnos que han utilizado de Colab: {freq_colab}")
print (f"Alumnos que han utilizado de GitHub: {freq_gh}")

Alumnos que han utilizado de Python: {'Si': 54, 'No': 6}
Alumnos que han utilizado de Colab: {'Si': 18, 'No': 42}
Alumnos que han utilizado de GitHub: {'Si': 52, 'No': 8}


In [63]:
# Tablas cruzadas (NumPy)
def tabla2x2(a, b):
    t = np.zeros((2,2), dtype=int) #np.zeros: Genera una matriz de 2 renglones y columnas rellenas de ceros
    t[1,1] = np.count_nonzero(a & b) #count_nonzero: Asigna la cuenta de los que no son 0
    t[1,0] = np.count_nonzero(a & ~b)
    t[0,1] = np.count_nonzero(~a & b)
    t[0,0] = np.count_nonzero(~a & ~b)
    return t

# Hace la multiplicacion boolean
tab_py_colab = tabla2x2(prog_py, usa_colab)
tab_py_gh    = tabla2x2(prog_py, cuenta_gh)
tab_colab_gh = tabla2x2(usa_colab, cuenta_gh)

In [64]:
print(f"Tabla Cruzada 2x2 de Python y Colab: \n{tab_py_colab}")

Tabla Cruzada 2x2 de Python y Colab: 
[[ 6  0]
 [36 18]]


In [65]:
print(f"Tabla Cruzada 2x2 de Python y GitHub: \n{tab_py_gh}")

Tabla Cruzada 2x2 de Python y GitHub: 
[[ 1  5]
 [ 7 47]]


In [66]:
# Medias de edad por grupo (NumPy)
means_by_group = {
    'edad_promedio_Python': {'Si': float(np.mean(edad[prog_py])) if np.any(prog_py) else np.nan,
                             'No': float(np.mean(edad[~prog_py])) if np.any(~prog_py) else np.nan},
    'edad_promedio_Colab':  {'Si': float(np.mean(edad[usa_colab])) if np.any(usa_colab) else np.nan,
                             'No': float(np.mean(edad[~usa_colab])) if np.any(~usa_colab) else np.nan},
    'edad_promedio_GitHub': {'Si': float(np.mean(edad[cuenta_gh])) if np.any(cuenta_gh) else np.nan,
                             'No': float(np.mean(edad[~cuenta_gh])) if np.any(~cuenta_gh) else np.nan},
}

summary_age, freq_python, freq_colab, freq_gh, tab_py_colab, tab_py_gh, tab_colab_gh, means_by_group

({'n': 60,
  'min': 20.0,
  'p25': 21.0,
  'mediana': 22.0,
  'media': 22.3,
  'p75': 23.0,
  'max': 26.0,
  'rango(ptp)': 6.0,
  'var_muestral': 1.8406779661016948,
  'std_muestral': 1.3567158752302173,
  'cv': 0.06083927691615324},
 {'Si': 54, 'No': 6},
 {'Si': 18, 'No': 42},
 {'Si': 52, 'No': 8},
 array([[ 6,  0],
        [36, 18]]),
 array([[ 1,  5],
        [ 7, 47]]),
 array([[ 5, 37],
        [ 3, 15]]),
 {'edad_promedio_Python': {'Si': 22.203703703703702, 'No': 23.166666666666668},
  'edad_promedio_Colab': {'Si': 22.11111111111111, 'No': 22.38095238095238},
  'edad_promedio_GitHub': {'Si': 22.21153846153846, 'No': 22.875}})

In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('/content/sample_data/doc.csv')
df.columns = [c.strip() for c in df.columns]

# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce') #coerce - Ignora
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/doc.csv'

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams["figure.dpi"] = 160
plt.style.use('seaborn-v0_8-whitegrid')

df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

accent  = '#2563eb'  # azul
accent2 = '#16a34a'  # verde
accent3 = '#f59e0b'  # ámbar
neutral = '#6b7280'  # gris

fig, ax = plt.subplots(figsize=(8,5))
bins = range(int(df['edad'].min())-1, int(df['edad'].max())+2)
ax.hist(df['edad'], bins=bins, color=accent, edgecolor='white', alpha=0.85)
mean_age = df['edad'].mean()
med_age = df['edad'].median()
ax.axvline(mean_age, color=accent2, linestyle='--', linewidth=2, label=f"Media: {mean_age:.2f}")
ax.axvline(med_age, color=accent3, linestyle=':', linewidth=2.5, label=f"Mediana: {med_age:.2f}")
ax.set_title('Distribución de las edades')
ax.set_xlabel('Edad (años)')
ax.set_ylabel('Frecuencia')
ax.legend()
plt.tight_layout()
plt.show()
fig.savefig('01_hist_edades.png', dpi=180)

In [ ]:
#2) Boxplot de edades
#El percentil va de 25 a 75
fig, ax = plt.subplots(figsize=(6,4))
ax.boxplot(df['edad'], vert=False, patch_artist=True,
           boxprops=dict(facecolor=accent, color=accent),
           medianprops=dict(color='white', linewidth=2),
           whiskerprops=dict(color=accent), capprops=dict(color=accent))
ax.set_title('Caja y bigotes: edad')
ax.set_xlabel('Edad (años)')
plt.tight_layout()
plt.show()
fig.savefig('02_box_edades.png', dpi=180)
#Bigotes presentan el resto de los datos

In [ ]:
df.head(3)

In [ ]:
# ====================================================
# 3) Barras: frecuencias de Sí/No para Python/Colab/GitHub
# ====================================================
fig, axes = plt.subplots(1,3, figsize=(12,4), sharey=True)
for ax, col, title, color in zip(
    axes,
    ['prog_python','usa_colab','cuenta_github'],
    ['Programó en Python','Usó Google Colab','Cuenta de GitHub'],
    [accent, accent2, accent3]
):
    counts = df[col].value_counts().reindex([True, False]).fillna(0).astype(int)
    labels = ['Sí','No']
    ax.bar(labels, counts, color=[color, neutral], edgecolor='white')
    ax.set_title(title)
    ax.set_ylim(0, max(counts.max(), 1)+2)
    for i, v in enumerate(counts):
        ax.text(i, v+0.1, str(v), ha='center', va='bottom', fontsize=9)
axes[0].set_ylabel('Número de estudiantes')
plt.tight_layout()
plt.show()
fig.savefig('03_barras_frecuencias.png', dpi=180)

In [ ]:
# =======================================
# 4) Mapas de calor 2x2 para combinaciones
# =======================================
pairs = [
    ('prog_python','usa_colab','Python vs Colab'),
    ('prog_python','cuenta_github','Python vs GitHub'),
    ('usa_colab','cuenta_github','Colab vs GitHub')
]

for idx, (a,b,titulo) in enumerate(pairs, start=1):
    a_bool = df[a].to_numpy(dtype=bool)
    b_bool = df[b].to_numpy(dtype=bool)
    t = np.zeros((2,2), dtype=int)
    t[1,1] = np.count_nonzero(a_bool & b_bool)
    t[1,0] = np.count_nonzero(a_bool & ~b_bool)
    t[0,1] = np.count_nonzero(~a_bool & b_bool)
    t[0,0] = np.count_nonzero(~a_bool & ~b_bool)

    fig, ax = plt.subplots(figsize=(5,4))
    im = ax.imshow(t, cmap='Blues')
    ax.set_title(f'Tabla 2×2: {titulo}')
    ax.set_xticks([0,1]); ax.set_xticklabels(['No','Sí'])
    ax.set_yticks([0,1]); ax.set_yticklabels(['No','Sí'])
    ax.set_xlabel(b); ax.set_ylabel(a)

    for i in range(2):
        for j in range(2):
            ax.text(j, i, t[i,j], ha='center', va='center',
                    color='black', fontsize=12, fontweight='bold')

    cbar = fig.colorbar(im, ax=ax)
    cbar.ax.set_ylabel('Conteo', rotation=270, labelpad=12)
    plt.tight_layout()
    plt.show()
    fig.savefig(f'04_heatmap_{idx}.png', dpi=180)

In [ ]:
# ======================================================
# 5) Barras: edad promedio por grupo (Sí/No) por variable
# ======================================================
fig, axes = plt.subplots(1,3, figsize=(12,4), sharey=True)
for ax, col, title, color in zip(
    axes,
    ['prog_python','usa_colab','cuenta_github'],
    ['Edad promedio por Python','Edad promedio por Colab','Edad promedio por GitHub'],
    [accent, accent2, accent3]
):
    means = df.groupby(col)['edad'].mean().reindex([True, False])
    labels = ['Sí','No']
    bars = ax.bar(labels, means, color=[color, neutral], edgecolor='white')
    for i, v in enumerate(means):
        ax.text(i, v+0.05, f"{v:.2f}", ha='center', va='bottom', fontsize=9)
    ax.set_title(title)
    ax.set_xlabel('Grupo')
axes[0].set_ylabel('Edad promedio (años)')
plt.tight_layout()
plt.show()
fig.savefig('05_barras_edad_promedio.png', dpi=180)

In [ ]:
# ===================================
# 6) Estadísticos de edad (impresión)
# ===================================
summary_age = {
    'n': int(df['edad'].size),
    'min': float(df['edad'].min()),
    'p25': float(np.percentile(df['edad'], 25)),
    'mediana': float(df['edad'].median()),
    'media': float(df['edad'].mean()),
    'p75': float(np.percentile(df['edad'], 75)),
    'max': float(df['edad'].max()),
    'rango(ptp)': float(np.ptp(df['edad'])),
    'var_muestral': float(np.var(df['edad'], ddof=1)),
    'std_muestral': float(np.std(df['edad'], ddof=1)),
    'cv': float(np.std(df['edad'], ddof=1)/np.mean(df['edad'])),
}
summary_age

MSE

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
anios_escolaridad = np.array([0, 3, 6, 9, 12, 16, 18])
ingreso_mensual_estimado_mx = np.array([12621, 15723, 19587, 24401, 30398, 40747, 47176])

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.scatter(anios_escolaridad, ingreso_mensual_estimado_mx) #Grafica scatter /Arreglo Lineal - X, Ingreso mensual estimado - Y
plt.title('Años de Escolaridad vs. Ingreso Mensual Estimado')
plt.xlabel('Años de Escolaridad')
plt.ylabel('Ingreso Mensual Estimado (MXN)')
plt.grid(True)
plt.show()

Primer intento de modelar los años de escolaridad y el ingreso estimado.   
Utilizar el primer punto y el útlimo para trazar una recta:   

$$ m = \frac{y_{2}-y_{1}}{x_{2}-x_{1}}$$   

$$ b= y_{1} - m * x_{1}$$

In [ ]:
x1 = anios_escolaridad[0]
y1 = ingreso_mensual_estimado_mx[0]
x2 = anios_escolaridad[-1]
y2 = ingreso_mensual_estimado_mx[-1]

m = (y2 - y1) / (x2 - x1) #Pendiente
b = y1 - m * x1  #Intersección

print(f"La ecuación de la recta es: y = {m:.2f}x + {b:.2f}")

In [ ]:
#Multiplica y suma por cada anio de escolaridad
linea_ingreso_estimado_new_plot = m * anios_escolaridad + b
linea_ingreso_estimado_new_plot

In [ ]:
import matplotlib.pyplot as plt

# Calcular los valores y de la recta utilizando m y b
linea_ingreso_estimado_new_plot = m * anios_escolaridad + b

plt.figure(figsize=(10, 6))
plt.scatter(anios_escolaridad, ingreso_mensual_estimado_mx, label='Datos Originales')
plt.plot(anios_escolaridad, linea_ingreso_estimado_new_plot, color='red', #Regresion de la recta
         label=f'Recta de Regresión (y = {m:.2f}x + {b:.2f})')
plt.title('Años de Escolaridad vs. Ingreso Mensual Estimado con Línea de Regresión')
plt.xlabel('Años de Escolaridad')
plt.ylabel('Ingreso Mensual Estimado (MXN)')
plt.grid(True)
plt.legend()
plt.show()
# Residuales son aquellos que estan debajo de la recta de regresion

Valores predichos
: Son los ingresos mensuales que nuestra recta de regresión predice para cada año de escolaridad.   

Errores (residuales): Es la diferencia entre el ingreso mensual real (ingreso_mensual_estimado_mx) y el ingreso mensual predicho (y_pred). Un error positivo significa que la predicción fue menor que el valor real, y un error negativo indica que la predicción fue mayor.   

Errores al cuadrado: Hemos elevado al cuadrado cada uno de los errores. Esto se hace para eliminar los signos negativos (de modo que los errores positivos y negativos no se cancelen entre sí) y para penalizar más los errores grandes.   

Suma de errores cuadrados: Es la suma de todos los errores al cuadrado. Este valor nos da una medida total de la 'distancia' de nuestros puntos a la línea.   

Error Cuadrático Medio (MSE): Es la suma de los errores cuadrados dividida por el número total de puntos de datos. El MSE es una medida promedio de la magnitud de los errores. Un MSE más bajo indica que el modelo se ajusta mejor a los datos.   

En este caso, el Error Cuadrático Medio (MSE) es de aproximadamente 13,196,667.31. Este número nos da una idea del rendimiento general de la recta que trazamos, mostrando la magnitud promedio de los errores al cuadrado entre los valores observados y los valores predichos por la línea.   

Fórmula del MSE (Error Cuadrático Medio) del Inglés Mean Squared Error   
SUMATORIA (valores reales - valores predichos) al cudarado   

$$ MSE = \frac{\Sigma_{i=1}^{n}(Y_{i}-\hat{Y_{i}})^{2}}{n}$$

Donde:
 $MSE = $error cuadrático medio.   
 $ n = $ número de datos.   
 $ Y_{i} = $ valores observados.   
 $ \hat{Y_{i}} = $valores predichos.   

In [ ]:
# 1. Calcular los valores predichos (y_pred) usando la ecuación de la recta
y_pred = m * anios_escolaridad + b
# Resultado es un vector
y_pred

In [ ]:
# 2. Calcular los errores (residuales): la diferencia entre los valores reales y los predichos
errores = ingreso_mensual_estimado_mx - y_pred
errores

In [ ]:
# 3. Elevar al cuadrado cada error
errores_cuadrados = errores**2
errores_cuadrados


In [ ]:
# 4. Sumar los errores cuadrados
suma_errores_cuadrados = np.sum(errores_cuadrados)
suma_errores_cuadrados

In [ ]:
# 5. Dividir la suma de los errores cuadrados por el número de puntos para obtener el MSE
mse = suma_errores_cuadrados / len(anios_escolaridad)
mse

Ahora comparemos el MSE de una regresión lineal.
Por ahora no es importante el detalle de la regrsión lineal.
Lo importante es comparar el MSE.

In [ ]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [ ]:
# Cambia la forma de anios_escolaridad a 2D array como es requerido por sklearn
X = anios_escolaridad.reshape(-1, 1)
y = ingreso_mensual_estimado_mx

X


In [ ]:
# Crear y ajustar el modelo de regresión lineal
modelo_regresion = LinearRegression()
modelo_regresion.fit(X, y)

# Obtener los coeficientes (m) e intercepto (b) del nuevo modelo
m_sklearn = modelo_regresion.coef_[0]
b_sklearn = modelo_regresion.intercept_

print(f"Coefficients (m) from scikit-learn: {m_sklearn:.2f}")
print(f"Intercept (b) from scikit-learn: {b_sklearn:.2f}")

El nuevo modelo de recta obtenido con regresión lineal es:   
$$ y = 1914.55 * x + 9731.66 $$

**Como ejercicios:**
* Grafica la línea del modelo de regresión lineal de sklearn junto con los datos originales.  
*   Calcula el MSE de esta regresión lineal y compara con el resultado anterior.   
*   ¿Cuál recta tiene menos error con respecto a los datos originales?.   

In [ ]:
#LINEA DEL MODELO DE REGRESIÓN LINEAL

import matplotlib.pyplot as plt

# Calcular los valores y de la recta utilizando m y b
linea_ingreso_estimado_new_plot = m_sklearn * anios_escolaridad + b_sklearn

plt.figure(figsize=(10, 6))
plt.scatter(anios_escolaridad, ingreso_mensual_estimado_mx, label='Datos Originales')
plt.plot(anios_escolaridad, linea_ingreso_estimado_new_plot, color='red',
         label=f'Recta de Regresión (y = {m:.2f}x + {b:.2f})')
plt.title('Años de Escolaridad vs. Ingreso Mensual Estimado con Línea de Regresión')
plt.xlabel('Años de Escolaridad')
plt.ylabel('Ingreso Mensual Estimado (MXN)')
plt.grid(True)
plt.legend()

In [68]:
#CALCULAR EL MSE
# 1. Calcular los valores predichos (y_pred) usando la ecuación de la recta
y_pred = m_sklearn * anios_escolaridad + b_sklearn
# Resultado es un vector
y_pred

# 2. Calcular los errores (residuales): la diferencia entre los valores reales y los predichos
errores = ingreso_mensual_estimado_mx - y_pred
errores

# 3. Elevar al cuadrado cada error
errores_cuadrados = errores**2
errores_cuadrados

# 4. Sumar los errores cuadrados
suma_errores_cuadrados = np.sum(errores_cuadrados)
suma_errores_cuadrados


# 5. Dividir la suma de los errores cuadrados por el número de puntos para obtener el MSE
mse = suma_errores_cuadrados / len(anios_escolaridad)
mse


*¿Cuál recta tiene menos error con respecto a los datos originales?*

Al comparar las dos rectas de regresión, la recta A presenta un MSE más alto que la recta B. Dado que el MSE de la recta B es menor, concluimos que esta recta tiene menos error y se ajusta mejor a los datos originales.
Por lo tanto, significa que sus predicciones tienen menor desviación respecto a los valores reales. Por lo tanto, el modelo asociado a la recta B logra un mejor ajuste.

Pandas

In [ ]:
import numpy as np #Arreglos
import pandas as pd #Para dataframes
#Serie de una dimension
#DataFrame es de una o más dimensiones

In [ ]:
s = pd.Series([1,2,5,np.nan,6,8])
s

In [ ]:
dates = pd.date_range("20130101", periods=6)
dates

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD")) #Le pasamos una lista
df

In [ ]:
df2 = pd.DataFrame(
    {
        "A": 1.0, #Le asignamos un escalar
        "B": pd.Timestamp("20130102"), #Le damos una fecha
        "C": pd.Series(1, index=list(range(4)), dtype="float32"), #Serie que el valor es uno que va hasta 3 de tipo flotante
        "D": np.array([3] * 4, dtype="int32"), #Lista con 4 tres
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

In [ ]:
df2.dtypes

In [ ]:
df.head(2)
#Trae los primeros datos

In [ ]:
#Trae los ultimos dos datos
df.tail(2)

In [ ]:
df.index

In [ ]:
df.columns

In [ ]:
df.to_numpy()

In [ ]:
df.describe()
# Persentil 25 es del 0 al 25%  de los datos

In [ ]:
df_edad = pd.read_csv('/content/sample_data/doc.csv')

In [ ]:
df_edad.info()

In [ ]:
df_edad.head()

In [ ]:
df_edad.rename({'¿Cuántos años cumplidos tienes?' : 'edad'}).head()

In [ ]:
df_edad.rename(columns={'¿Cuántos años cumplidos tienes?' : 'edad'}).head()

In [ ]:
df_edad.describe()

In [69]:
#FRECUENCIA DE LAS EDADES
df_edad['edad'].value_counts()
#Para ordenar de menor a mayor edad
df_edad['edad'].value_counts().sort_index()
#Para mostrar el porcentaje
df_edad['edad'].value_counts(normalize=True) * 100


NameError: name 'df_edad' is not defined