<a href="https://colab.research.google.com/github/Ivon110/Mineria-de-Datos/blob/main/mineriacolab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos


##**Primer Parcial**

### Introducción




####Conceptos

La minería de datos es el proceso de extraer información útil a partir de una acumulación de datos, a menudo provenientes de un almacén o de una recopilación de data sets vinculados. Las herramientas para minería de datos incluyen potentes capacidades estadísticas, matemáticas y analíticas cuyo propósito principal es examinar grandes data sets para identificar tendencias, patrones y relaciones a fin de dar soporte a la toma de decisiones y planificación fundamentadas.

#### Ciencia de Datos

Libro

La ciencia de datos es un campo interdisciplinario que combina matemáticas, estadística, programación, inteligencia artificial (IA) y aprendizaje automático (machine learning) para analizar grandes volúmenes de datos estructurados y no estructurados. Su objetivo principal es extraer información valiosa que permita tomar decisiones estratégicas y resolver problemas empresariales.

IPython Magix Commands


In [ ]:
# El comando magico %timeit sirve para evaluar el desempeño, en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

118 µs ± 39.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#El comando magico %%timeit sirve para evaluar el desempeño, en terminos de tiempo
# Solo que este abarca varias lineas de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

79.2 µs ± 2.01 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
#Para ver las variables de entorno/ambiente
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '8dd22b69d4bd',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Undestanding Data Types In Python

In [ ]:
import numpy as np

In [ ]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
#float 32 para la precision del flotante
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1,2,3,4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
np.array([range(i, i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The Basics of NumPy Arrays

In [1]:
#Importamos NumPy
import numpy as np

In [3]:
#Generamos una semilla aleatoria
np.random.seed(0)
# Generamos un arreglo aleatorio de enteros, de tamaño seis
x1 = np.random.randint(10, size=6) #El superior no se toma en cuenta es decir va del 0 al 9
# Generamos un arreglo aleatorio de enteros, de tamaño tres renglones y cuatro columnas
x2 = np.random.randint(10, size=(3,4))
# Para hacer un arreglo tridimensional
x3 = np.random.randint(10, size=(3,4,5))

In [6]:
print("x3 ndim: ", x3.ndim) # ndim nos dice el numero de dimensiones (x3 tiene 3 dimensiones)
print("x3 shape:", x3.shape) # shape imprime su forma, regresa lo que contiene la lista
print("x3 size: ", x3.size) # size es la multiplicacion del shape 3x4=12 x 5 = 60

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print(x2.dtype) # dtype nos dice el tamaño en bytes de cada arreglo

int64


In [8]:
#itemsize: Lista el tamaño (en bytes) de cada arreglo
print("itemsize:", x3.itemsize, "bytes")
# nbytes: Lista el tamaño total (en bytes) del arreglo
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [9]:
# Son digitos entre el 0 y 10 porque le dimos este limite desde el principio (x1 = np.random.randint(10, size=6) )

x1

array([5, 0, 3, 3, 7, 9])

In [10]:
#Colocamos el índice del elemento a extraer, en este caso el primer elemento tiene el índice 0
x1[0]

np.int64(5)

In [11]:
#Colocamos el índice del elemento a extraer, en este caso el quinto elemento tiene el índice 4
x1[4]

np.int64(7)

In [12]:
# Si queremos el ultimo elemento de ndarray (Arreglo de n dimensiones) podemos poner -1 de índice
x1[-1]

np.int64(9)

In [13]:
#Array Multidimensional
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [14]:
#Colocamos el índice del elemento a extraer, en este caso el primer elemento tiene el índice 0,0 para un indice multidimensional
x2[0,0]

np.int64(3)

In [16]:
# Renglon es la fila
# Renglon,Columna
x2[0,2]

np.int64(2)

In [21]:
x2[0,0] = 12 # Asignar un nuevo valor al renglon 0 columna 0
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1, 12,  7,  7]])

#### Estadística Básica